mmseq : mm-seq.cpp
	g++ mm-seq.cpp -o mmseq.out
mmsem : mm-pthreads.semaphores.cpp
	g++ -lpthread mm-pthreads.semaphores.cpp -o mmsem.out
mmmtx : mm-pthreads.cpp
	g++ -lpthread mm-pthreads.cpp -o mmmtx.out
