mmmtx : mm-pthreads.mutex.cpp
	g++ -lpthread mm-pthreads.mutex.cpp -o mmmtx.out
mmts : mm-ts.cpp
	g++ -lpthread mm-ts.cpp -o mmts.out
mmseq : mm-seq.cpp
	g++ mm-seq.cpp -o mmseq.out
mmsem : mm-pthreads.semaphores.cpp
	g++ -lpthread mm-pthreads.semaphores.cpp -o mmsem.out
